---
title: "DSC Analysis"
output: html_notebook
## Date: 05/01/2023
editor_options: 
  chunk_output_type: inline
---

```{r}

# Load Libraries
library(tidyverse)
library(here)
library(kableExtra)
library(ggpubr)
library (dbplyr)
library(stringr)
library(haven)

```

```{r}
# Data Loading ----
## Loading the paths
files <- 
  here::here("Data") %>%
  dir( recursive=TRUE, full.names=TRUE, pattern="\\.txt$")
```

```{r}

### Function to identify the names of the data ----
names <- 
  here::here("Data") %>%
  dir( recursive=TRUE, pattern="\\.txt$")
```
```{r}
data_trans<- files %>% map( ~ read.delim (., skip = 9,  ))
data_trans <- data_trans %>% set_names(names) %>% enframe ("Material", "Datos")
data_trans<-data_trans %>% 
  separate(Material,
             sep = "/",
             into = c("Material","file"))
data_trans$file <- NULL
```


```{r}
df <- data_trans %>%  
  separate.data.frame (data_trans [[2]][[1]],
            c("index","T[s]","Ts[°C ]", "Tr[°C ]","Value [Wg^-1]"))

```







Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
